---
- block:
  # https://git.io/fN3Fm
  - name: 'Set the maintenance mode'
    command: ghe-maintenance -s
    register: ghe_maintenance_set
    failed_when: ghe_maintenance_set.rc != 0

  - debug:
      msg: '{{ ghe_maintenance_set }}'
      verbosity: 2

  - set_fact: ghe_maintenance_mode_enabled='{{ ghe_maintenance_set.failed == false }}'

  - debug:
      msg: '{{ ghe_maintenance_mode_enabled }}'
      verbosity: 2

  delegate_to: github_primary
  when: ghe.primary_ip != False
